# Generated by Django 4.2.3 on 2023-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('released_at', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_number', models.SmallIntegerField(default=0)),
                ('track_title', models.CharField(default=1, max_length=30)),
                ('album', models.ManyToManyField(max_length=30, related_name='tracks', to='music.album')),
            ],
        ),
    ]
