# Generated by Django 4.2.3 on 2023-07-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_track_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album_bonus',
            field=models.ManyToManyField(max_length=30, related_name='tracks', to='music.album'),
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='music.album'),
        ),
    ]
