# Generated by Django 4.2.3 on 2023-07-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_album_bonus_remove_track_album_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_number',
            new_name='track_no',
        ),
    ]
