# Generated by Django 4.2.3 on 2023-07-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_album_tags_delete_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='tags',
            new_name='tag',
        ),
    ]
